<?php
	include('portail.php');
	include('forum.php');
	include('connected.php');
	include('slider.php');
	include('register.php');
	include('help.php');
	include('admin.php');
	include('get.php');
	include('profil.php');
	include('boutique.php');
	include('news.php');
?>